# Permalinks
markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

# Setup
title:            Jiten Thakkar
url:              http://jiten-thakkar.com
paginate:         1
baseurl:          http://jiten-thakkar.github.io/
author:
  name:           Jiten Thakkar
  url:            https://twitter.com/jiten_mt
  email:          jitenmt@gmail.com

name: 		  Jiten Thakkar
twitter:	  jiten_mt

# Custom vars
version:          2.0.0
github:
  repo:           https://github.com/jiten-thakkar/jiten-thakkar.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  
  # Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
