---
permalink: /posts/:title
rdiscount:
  extensions:
  - smart
title: Jiten Thakkar
url: https://jiten-thakkar.com
baseurl: ""
paginate: 1
author:
  name: Jiten Thakkar
  url: https://twitter.com/jiten_mt
  email: jitenmt@gmail.com
name: Jiten Thakkar
twitter: jiten_mt
version: 2.0.0
github:
  repo: https://github.com/jiten-thakkar/jiten-thakkar.github.io
pages_list:
  About: /about/
  Archive: /archive/
gems:
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-admin
- jekyll-paginate
