# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jiten Thakkar
tagline:          'Mozilla, GSoC, Cool Stuff'
url:              http://getpoole.com
paginate:         1
baseurl:          http://jiten-thakkar.github.io/
author:
  name:           Jiten Thakkar
  url:            https://twitter.com/jiten_mt
  email:          jitenmt@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jiten-thakkar/jiten-thakkar.github.io
